// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import context "context"
import domain "github.com/bxcodec/go-clean-arch/domain"
import mock "github.com/stretchr/testify/mock"

// LogmovieRepository is an autogenerated mock type for the LogmovieRepository type
type LogmovieRepository struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *LogmovieRepository) GetByID(ctx context.Context, id int64) (domain.Logmovie, error) {
	ret := _m.Called(ctx, id)

	var r0 domain.Logmovie
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Logmovie); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Logmovie)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
